"""
Quantro Personal AI — Constants
"""

# Market
MARKET_OPEN_HOUR = 9
MARKET_OPEN_MINUTE = 15
MARKET_CLOSE_HOUR = 15
MARKET_CLOSE_MINUTE = 30
TIMEZONE = "Asia/Kolkata"

# Timeframes
TIMEFRAME_DAILY = "daily"
TIMEFRAME_1H = "1h"
TIMEFRAME_15M = "15m"
TIMEFRAME_5M = "5m"

# Default Limits
DEFAULT_PAGINATION_LIMIT = 50
MAX_PAGINATION_LIMIT = 200

# Cache Expiry (seconds)
CACHE_EXPIRY_PRICE = 60      # 1 minute
CACHE_EXPIRY_REGIME = 3600   # 1 hour
CACHE_EXPIRY_SECTORS = 86400 # 24 hours

# Indicator Periods
DEFAULT_RSI_PERIOD = 14
DEFAULT_MACD_FAST = 12
DEFAULT_MACD_SLOW = 26
DEFAULT_MACD_SIGNAL = 9
DEFAULT_ATR_PERIOD = 14
DEFAULT_BOLLINGER_PERIOD = 20
DEFAULT_BOLLINGER_STD = 2

# Risk Defaults
MAX_LEVERAGE = 1.0  # Cash market default
